# Generated by Django 5.2.1 on 2025-06-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_pickuppoint_promocode_remove_toy_toy_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название производителя')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='toy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toys/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='toy',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toys', to='production.manufacturer', verbose_name='Производитель'),
        ),
    ]
