# Generated by Django 5.2.1 on 2025-06-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_manufacturer_toy_image_toy_manufacturer'),
        ('promotions', '0002_promocode_discount_percent_alter_promocode_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promocode'),
        ),
    ]
