# Generated by Django 5.2.6 on 2025-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('event', models.TextField(verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Историческое событие',
                'verbose_name_plural': 'История компании',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнёра')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('website', models.URLField(verbose_name='Сайт партнёра')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinformation',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='certificate_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись к сертификату'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_certs/', verbose_name='Изображение сертификата'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company_video/', verbose_name='Видео-презентация'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='description',
            field=models.TextField(verbose_name='Описание компании'),
        ),
    ]
