# Generated by Django 5.2.6 on 2025-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0002_companyhistory_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок слайда')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Изображение')),
                ('link', models.CharField(default='#', max_length=255, verbose_name='Ссылка при клике (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveIntegerField(default=5000, help_text='Введите время в миллисекундах (например, 5000 = 5 сек)', verbose_name='Время показа слайда (мс)')),
                ('is_auto', models.BooleanField(default=True, verbose_name='Автоматическое переключение')),
                ('is_loop', models.BooleanField(default=True, verbose_name='Бесконечная прокрутка')),
            ],
            options={
                'verbose_name': 'Настройки слайдера',
                'verbose_name_plural': 'Настройки слайдера',
            },
        ),
    ]
