# Generated by Django 5.2.1 on 2025-05-21 16:07

import real_estate.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
            bases=(models.Model, real_estate.mixins.SlugMixin),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('contract_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='object/')),
                ('category', models.ManyToManyField(to='real_estate.objectcategory')),
            ],
            bases=(models.Model, real_estate.mixins.SlugMixin),
        ),
    ]
