# Generated by Django 5.2.1 on 2025-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateobject',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
