# Generated by Django 5.2.1 on 2025-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='ДД/ММ/ГГГГ', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('client', 'Клиент'), ('employee', 'Сотрудник')], default='client', max_length=100),
        ),
    ]
