# Generated by Django 5.2.1 on 2025-05-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], max_length=10)),
            ],
        ),
    ]
