# Generated by Django 5.2.1 on 2025-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='state',
            field=models.CharField(choices=[('active', 'Активен'), ('archive', 'Архив')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='text',
            field=models.CharField(max_length=50, unique=True, verbose_name='Промокод'),
        ),
    ]
