# Generated by Django 5.2.1 on 2025-06-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('client', 'Клиент'), ('employee', 'Сотрудник')], default='client', max_length=100, verbose_name='Роль'),
        ),
    ]
